vacabulary = {"&&" => "and",
              "||" => "or",
              "!" => "not",
              "!=" => "not equal",
              "==" => "equal",
              ">=" => "greater than or equal",
              "<=" => "less than or equal"}

tables = {"!false" => "true",
          "!true" => "false",
          "true || false" => "true",
          "true || true" => "true",
          "false || true" => "true",
          "false || false" => "false",
          "true && false" => "false",
          "true && true" => "true",
          "false && true" => "false",
          "false && false" => "false",
          "!(true || false)" => "false",
          "!(true || true)" => "false",
          "!{false || true}" => "false",
          "!(false || false)" => "true",
          "!(true && false)" => "true",
          "!(true && true)" => "false",
          "!(false && true)" => "true",
          "!(false && false)" => "true",
          "0 != 1" => "true",
          "1 != 1" => "false",
          "1 != 0" => "True",
          "0 != 0" => "false",
          "0 == 1" => "false",
          "1 == 1" => "true",
          "1 == 0" => "false",
          "1 == 1" => "true"}
