animals = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']

# 1. The animal at 1...
# is the second animal, ruby. (Is this a clever/ naive joke on python?)
# 2. The third animal...
# is at 2 and it's a peacock.
# 3. The first animal...
# is at 0 and it's a bear.
# 4. The animal at 3...
# is the fourth animal and it's a kangaroo.
# The fifth animal...
# is at 4 and it's a whale.
# The animal at 2...
# is the third animal and it's a peacock.
# The sixth animal...
# is at 5 and and it's a platypus.
