# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c84e4e6fe88cb278aa7cbdcada56e8fd8adedfdb838cc4c7391ccd0d6670f3771d6e294d730e03f62934836fcc6adcb5fd285e956b6399e230a24d50dfd482

test:
  secret_key_base: 61c32675cc4a9da3685a67142f57463859154c2b45f1a15bf151695604b6338eceaa9b0b37df50cfac04ac9b4f9d3d6252737066b883e1cac99a30662bf8b08d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
